services:
  jawas-kamino:
    build: .
    container_name: jawas-kamino
    environment:
      - TARGET_PROTOCOL=KAMINO
      - LOG_FILE=kamino_raw.jsonl
      - SOLANA_KEYPAIR_PATH=/app/secrets/keypair.json
    env_file:
      - .env
    volumes:
      - ./secrets:/app/secrets:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  jawas-solend:
    build: .
    container_name: jawas-solend
    environment:
      - TARGET_PROTOCOL=SOLEND
      - LOG_FILE=solend_raw.jsonl
      - SOLANA_KEYPAIR_PATH=/app/secrets/keypair.json
    env_file:
      - .env
    volumes:
      - ./secrets:/app/secrets:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
